export const GET_ALL_CATEGORY_ERROR = 'GET_ALL_CATEGORY_ERROR';
export const GET_ALL_CATEGORY_FETCHING = 'GET_ALL_CATEGORY_FETCHING';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';

export const REMOVE_CATEGORY_BY_ID = 'REMOVE_CATEGORY_BY_ID';
export const ADD_CATEGORY = 'ADD_CATEGORY';
