export const GET_POST_FETCHING = 'GET_POST_FETCHING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const GET_POST_BYID_FETCHING = 'GET_POST_BYID_FETCHING';
export const GET_POST_BYID_SUCCESS = 'GET_POST_BYID_SUCCESS';
export const GET_POST_BYID_ERROR = 'GET_POST_BYID_ERROR';

export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';