export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const USER_FETCHING = 'USER_FETCHING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';